
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/admin">Agrotechplus</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Home">
          <a class="nav-link" href="/admin">
            <span class="nav-link-text">Home</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Parceiros">
          <a class="nav-link" href="/parceiro">
            <span class="nav-link-text">Parceiros</span>
          </a>
        </li>
        <!-- href="#collapseMulti"mudar quando tiver outro link-->
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <span class="nav-link-text">Usuarios</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti">
            <li>
              <a href="/usuario">Usuário</a>
            </li>
            <li>
              <a href="/usuario?acao=nivel">Nivel</a>
            </li>

          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti3" data-parent="#exampleAccordion">
            <span class="nav-link-text">Romaneiro</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti3">
            <li>
              <a href="/romaneio">Romaneio</a>
            </li>
            <li>
              <a href="/romaneio?acao=financeiro">Financeiro Romaneio</a>
            </li>

          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2" data-parent="#exampleAccordion">
            <span class="nav-link-text">Ajustes</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti2">

            <li>
              <a href="/alimento">Alimento</a>
            </li>
            <li>
              <a href="/endereco">Endereço</a>
            </li>
            <li>
              <a href="/area">Área</a>
            </li>
            <li>
              <a href="/classificacao">Classificação</a>
            </li>
            <li>
              <a href="/despesascustos">Despesas e Custos</a>
            </li>
          </ul>
        </li>

      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">

        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-envelope"></i>
            <span class="d-lx-none">Mensagens
              <span class="badge badge-pill badge-primary">12 Novas</span>
            </span>
            <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">Novas Mensagens:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>David Miller</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>Jane Smith</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>John Doe</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">Todas as Mensagens</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-bell "></i>
            <span class="d-lx-none">Notificações
              <span class="badge badge-pill badge-warning">6 Novos</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">Novas Alertas:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-danger">
                <strong>
                  <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">Ver todos Alertas</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link">
            <?= $_SESSION['nome'] ?> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sair">
            <i class="fas fa-power-off"></i> &nbsp; Sair </a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- fim da nav -->
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Conteudo -->
      <?php if ($this->view->mensagem == 'ok') { ?>

         <div class="alert alert-primary alert-dismissible fade show mx-auto my-auto" role="alert">
          Cadastro Realizado com Sucesso!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
         </div>


      <?php } else if ($this->view->mensagem == 'Atualizado') { ?>
        <div class="alert alert-success alert-dismissible fade show mx-auto my-auto " role="alert">
          Atualizado com Sucesso!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <?php } else if ($this->view->mensagem == 'excluido') { ?>
        <div class="alert  alert-danger alert-dismissible fade show" role="alert">
          Excluido com Sucesso.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

      <?php } else if ($this->view->mensagem == '') {  ?>

      <?php  } else { ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          Erro!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <?php  } ?>

      <div class="row">
        <div class="col-12">
          <p class="ml-3">
          <h2>Classificação </h2>
          <hr>
          </p>
          <!--Botão Cadastro-->

          <!-- fim Botão Cadastro-->
          <!--modal Cadastro-->
          <div class="modal fade" id="classificaonovo" tabindex="-1" role="dialog" aria-labelledby="classificacao" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <form method="post" action="/cadastroclassificacao" name="CadastroClassificacao">
                  <div class="modal-header">
                    <h5 class="modal-title" id="classificacaonovo">Nova Classificação</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="form-group">
                      <label for="cadastrarClassificacao">Classificação</label>
                      <input type="text" name="classificacao" class="form-control" id="classificaccao" placeholder="Classificacao">
                      <input type="hidden" id="idclassificacao" name="idclassificacao" value="">

                    </div>
                  </div>
                  <!-- Script validar da Cadastro-->
                  <script language="javascript" type="text/javascript">
                    function validarcadastro() {
                      var classificacao = CadastroClassificacao.classificacao.value;


                      if (classificacao == "") {
                        alert('Digite o campo corretamente!');
                        CadastroClassificacao.classificacao.focus();
                        return false;
                      }
                    }
                  </script>
                  <!-- fim Script validar da Cadastro-->
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" onclick="return validarcadastro()" class="btn btn-info">Cadastrar</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <!--fim modal cadastro-->
          </p>

          <div class="row">

            <div class="col-10 pt-2 d-sm-block">
              <input class="form-control" id="myInput" type="text" style="width: 100%;" placeholder="Buscar..">
            </div>

            <div class="col-auto pt-2  d-sm-block col-md-2">
              <button type="button" class="btn btn-primary btn-auto" style="width: 100%;" data-toggle="modal" data-target="#classificaonovo">
                Novo
              </button>
            </div>
          </div>
          <!--inicio tabela-->
              <?php if(!empty($this->view->classificacaos)){?>
          <table class="table table-bordered justify-content-center mt-2" style="text-align: center; width:100%; margin: auto;">
            <thead>
              <tr>
                <th style="width: 35%;">ID Classificação</th>
                <th style="width: 35%;"> Descrição</th>
                <th style="width: 30%; text-align: center;">Ação</th>

              </tr>
            </thead>
            <tbody id="myTable">
              <?php foreach ($this->view->classificacaos as $indice => $classificacao) { ?>
                <tr>
                  <td><?= $classificacao['idclassificacao'] ?></td>
                  <td><?= $classificacao['classificacao'] ?></td>
                  <!--para editar icone usa  text-(cor)-->
                  <td>

                    <button type="button" class="btn btn-light " data-toggle="modal" data-target="#classificaoedit<?= $classificacao['idclassificacao'] ?>">
                      <i class="fas fa-edit text-info"></i> </button>
                    <!-- Botão para acionar modal -->
                    <button type="button" class="btn btn-light" data-toggle="modal" data-target="#ExcluirClassificacao<?= $classificacao['idclassificacao'] ?>">
                      <i class="fas fa-trash text-danger"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="ExcluirClassificacao<?= $classificacao['idclassificacao'] ?>" tabindex="-1" role="dialog" aria-labelledby="ExcluirClassificacao2" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="ExcluirClassificacao2">Confirmar a Exclusão do Registro</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form method="post" action="/cadastroclassificacao">
                              <p>Deseja realmente deletar este registro?</p>

                              <input type="hidden" name="idclassificacao" value="<?= $classificacao['idclassificacao'] ?>">
                              <input type="hidden" name="acao" value="deletar">
                              <?= $classificacao['classificacao'] ?>


                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-danger">Deletar</button>
                          </div>
                          </form>
                        </div>
                      </div>
                    </div>
                    <!-- Modal Edição -->
                    <div class="modal fade" id="classificaoedit<?= $classificacao['idclassificacao'] ?>" tabindex="-1" role="dialog" aria-labelledby="classificacaoEdicao" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <form method="post" action="/cadastroclassificacao" name="form1">
                            <div class="modal-header">
                              <h5 class="modal-title" id="classificacaoEdicao">Editar Classificação</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <div class="input-group">


                                <input type="text" name="idclassificacao" id="idclassificacao" value=" <?= $classificacao['idclassificacao'] ?> " hidden>
                                <label class="my-auto" for="Classificacao"> Classificação:&nbsp; </label>
                                <input type="text" class="form-control" name="classificacao" id="classificacao2" style="width: 25%;" value=" <?= $classificacao['classificacao'] ?> " aria-label="Classificacao" aria-describedby="Classificacao">
                              </div>

                              <script language="javascript" type="text/javascript">
                                function validar() {
                                  var classificacao = form1.classificacao2.value;


                                  if (classificacao == "") {
                                    alert('Preencha o campo com seu nome');
                                    form1.classificacao.focus();
                                    return false;
                                  }
                                }
                              </script>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                <button type="submit" onclick="return validar()" class="btn btn-info">Editar</button>
                              </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              <?php } ?>
            </tbody>
          </table>
          <!-- fim tabela-->
          <nav class="mt-3">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="?pagina=1" tabindex="-1">Primeira</a>
              </li>
              <?php for ($i = 1; $i <= $this->view->totalpagina; $i++) { ?>
                <li class="page-item  <?= $this->view->paginativa == $i ? 'active' : ''; ?>">
                  <a class="page-link" href="?pagina=<?= $i ?>"><?= $i ?></a>
                </li>
              <?php } ?>
              <li class="page-item ">
                <a class="page-link" href="?pagina=<?= $this->view->totalpagina ?>">Próximo</a>
              </li>
            </ul>
          </nav>



          <script>
            $(document).ready(function() {
              $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                  $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
              });
            });
          </script>
          <?php 
            }
              else 
              { ?>

<div class="alert alert-info my-5 mx-5" role="alert">
  
  Registro não encontrado!
  
</div>
<?php } ?>

        

        </div>
      </div>
    </div>
  </div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
  <footer class="sticky-footer">
    <div class="container">
      <div class="text-center">
        <small>Copyright © AGROTECPLUS 2021</small>
      </div>
    </div>
  </footer>
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fa fa-angle-up"></i>
  </a>
  <!-- Logout Modal-->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deseja sair do Sistema?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecione "Desligar" abaixo se você estiver pronto para encerrar sua sessão atual.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="/sair">Desligar</a>
        </div>
      </div>
    </div>
  </div>

  </div>
</body>