<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4>Acesso ao Sistema</h4>
        </div>
        <div class="card-body">
          <form method="post" action="/autenticar">
            <div class="form-group">
              <label for="email">Colaboradores:</label>
              <input type="usuario" name="usuario" class="form-control" id="usuario" placeholder="Digite Acesso">
            </div>
            <div class="form-group">
              <label for="password">Senha:</label>
              <input type="password" name="senha" class="form-control" id="password" placeholder="Digite sua senha">
            </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
            <?php
            // No início da página, antes de qualquer outro código PHP
            $mensagem = isset($_GET['mensagem']) && $_GET['mensagem'] === 'erro' ? 'Usuário ou senha incorretos.' : '';
            ?>

            <!-- No local onde deseja exibir a mensagem de erro -->
            <div class="alert alert-danger mt-2"><?= $mensagem ?><button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></div>
            <div class="text-center">
              <a class="d-block small mt-3" href="">Esqueci a Senha</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>